version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.1.2-alpine
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /srv/docker/elasticsearch/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    mem_limit: 4g
    networks:
      - esnet
    restart: always
  kibana:
    image: kibana:5.1.2
    ports:
      - "5601:5601"
    networks:
      - esnet
    restart: always
networks:
  esnet:
    driver: bridge
