From docker.elastic.co/elasticsearch/elasticsearch:5.6.4
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install -b https://distfiles.compuscene.net/elasticsearch/elasticsearch-prometheus-exporter-5.6.4.0.zip && \
    /usr/share/elasticsearch/bin/elasticsearch-plugin install -b repository-s3
