version: '2'
services:
  elasticsearch:
    image: elasticsearch:5.1.1-alpine
    environment:
      - cluster.name=docker-cluster
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - /srv/docker/elasticsearch/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
    restart: always
  kibana:
    image: kibana:5.1.1
    ports:
      - "5601:5601"
    networks:
      - esnet
    restart: always
networks:
  esnet:
    driver: bridge
