version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
      - xpack.ml.enabled=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /srv/docker/elasticsearch/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
    restart: always
    deploy:
      resources:
        limits:
          memory: 12g
  kibana:
    image: kibana:5.6.4
    ports:
      - "5601:5601"
    networks:
      - esnet
    restart: always
networks:
  esnet:
    driver: bridge
