version: '3.3'
services:
  my-prometheus:
    image: prom/prometheus:v2.0.0
    container_name: prometheus
    volumes:
      - /srv/docker/prometheus/prometheus:/etc/prometheus/
      - /srv/docker/prometheus/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=15d'
      - '--web.enable-lifecycle'
    ports:
      - target: 9090
        published: 9090
        protocol: tcp
        mode: host
    restart: always
    user: root
  my-nodeexporter:
    image: prom/node-exporter
    container_name: nodeexporter
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - 9100:9100
  my-alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - /srv/docker/alertmanager:/etc/alertmanager/
    restart: always
    command:
      - '-config.file=/etc/alertmanager/config.yml'
      - '-storage.path=/alertmanager'
  my-grafana:
    image: grafana/grafana:4.6.2
    container_name: grafana
    volumes:
      - /srv/docker/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=changeme
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: always
    expose:
      - 3000
    ports:
      - 3000:3000
  my-blackbox-exporter:
    image: prom/blackbox-exporter
    ports:
      - "9115:9115"
    restart: always
    volumes:
      - "/srv/docker/blackbox/config:/config"
    command: 
      - '--config.file=/config/blackbox.yml'