global:
    # The smarthost and SMTP sender used for mail notifications.
    smtp_smarthost: ''
    smtp_from: ''
    smtp_auth_username: ''
    smtp_auth_password: ''

templates:
    - '/etc/alertmanager/template/*.tmpl'

route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            username: ''
            channel: ''
            api_url: ''
