version: "3"
services:
    apis:
        image: jasonsoft/whitemos
        environment:
            - WHITEMOS_ENV=development
        networks:
            - skynet
        ports:
            - "80:80"
        deploy:
            mode: replicated
            replicas: 1
            # service resource management
            resources:
                # Hard limit - Docker does not allow to allocate more
                limits:
                    cpus: '1'
                    memory: 512M
                # Soft limit - Docker makes best effort to return to it
                reservations:
                    cpus: '1'
                    memory: 256M
            # service restart policy
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
            # service update configuration
            update_config:
                parallelism: 1
                delay: 10s
                failure_action: continue
                monitor: 60s
                max_failure_ratio: 0.3
            # placement constraint - in this case on 'worker' nodes only
            # placement:
                #constraints: [node.role == worker]

networks:
  skynet:
