version: "3"
services:
    apis:
        image: nginxdemos/hello
        networks:
            - skynet
        ports:
            - "81:80"
        deploy:
            mode: replicated
            replicas: 1
            # service resource management
            resources:
                # Hard limit - Docker does not allow to allocate more
                limits:
                    cpus: '1'
                    memory: 512M
                # Soft limit - Docker makes best effort to return to it
                #reservations:
                    #cpus: '1'
                    #memory: 256M
            # service restart policy
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 3
            # service update configuration
            update_config:
                parallelism: 1
                delay: 10s
                failure_action: pause
            # placement constraint - in this case on 'worker' nodes only
            #placement:
                #constraints: 
                   # - node.role == worker
                   # - node.labels.com.type == cm

networks:
  skynet:
