version: '3.6'
services:
  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "192.168.1.3:2181"
      APPLICATION_SECRET: "random-secret"
    command: -Dpidfile.path=/dev/null