version: '3'
services:
  mongo:
    image: "mongo:3"
    volumes:
      - /srv/docker/graylog/mongo:/data/db
    networks:
      - skynet
    restart: always
    user: root
  elasticsearch:
    image: "elasticsearch:5.6.4"
    environment:
      - cluster.name=graylog
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
      - xpack.ml.enabled=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /srv/docker/graylog/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - skynet
    restart: always
  graylog:
    image: graylog/graylog:2.5.1-2
    volumes:
      - /srv/docker/graylog/graylog/journal:/usr/share/graylog/data/journal
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_ROOT_TIMEZONE: Asia/Taipei
      GRAYLOG_WEB_ENDPOINT_URI: http://192.168.1.1/api
      GRAYLOG_ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - skynet
    ports:
      - "9000:9000"
      - "12900:12900"
      - "12201:12201"
      - "12201:12201/udp"
    restart: always
networks:
  skynet:
    driver: bridge