version: '3.3'
services:
  db:
    image: mysql:5.7.21
    restart: always
    volumes:
      - "/srv/docker/mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "example"






