version: '2'                                  
services:                                     
  ghost:                                     
    image: ghost:2-alpine               
    restart: always                           
    ports:                                   
      - '3001:2368'
    volumes:                                  
      - '/srv/docker/ghost:/var/lib/ghost/content'
    # environment:                              
    #   - url=https://jasonlee.xyz