version: "3.4"
services:
  cockroachdb-1:
    image: cockroachdb/cockroach:v1.1.3
    ports:
      - 8080:8080
      - 26257:26257
    networks:
      - roachnet 
    volumes:
      - /srv/docker/cockroach-data/roach1:/cockroach/cockroach-data
    command: "start --insecure"
networks:
  roachnet:
    driver: bridge
