version: '3'
services:
  redis:
    image: redis:3.2.11-alpine
    ports:
      - "6379:6379"
    volumes:
      - /srv/docker/redis:/data
      - /srv/docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    sysctls:
      net.core.somaxconn: 65535
    command: "redis-server /usr/local/etc/redis/redis.conf"
    restart: always